# Generated by Django 5.1.4 on 2025-01-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
