# Generated by Django 5.1.4 on 2025-01-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_productreview_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
